version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth-server
    ports:
      - 5432:5432

volumes:
  db-data:
